### ISSUE TITLE
Order of  "unlocked_by": null elements determines graph edges _together_ with "unlocked_by": "..."

### ISSUE THREAD

**Issue by katrinleinweber** [jonmcalder/exercism-config-viz#1]
To specify the issue I mentioned in https://github.com/exercism/r/pull/127#issuecomment-526721070: I'm seeing cycles/loops, for example when I set `bob` to `"unlocked_by": "anagram"`:

![Screen Shot 2019-08-30 at 21 41 16](https://user-images.githubusercontent.com/9948149/64047866-47081b00-cb70-11e9-8cea-04d62e6e10a7.png)

Could there be a bug here somewhere: https://github.com/jonmcalder/exercism-config-viz/blob/e21da67dd24c6ccd00c54ecf22733ff7594d0703/server.R#L72-L76 ? Maybe with the `is.na()`? Does it return a sensible result when the `null`s from the JSON are fed into it?

**Comment by jonmcalder** [comment]
Updating `bob` to be unlocked_by `anagram` will only yield the above result if you forget to also set "core": false for `bob`.

Did you maybe overlook that? By definition a core exercise should unlocked by something else, so if you leave `bob` as core then I think it defaults to being unlocked by the core exercise which precedes it in the json.

**Comment by katrinleinweber** [comment]
Should have taken more screenshots. Even when I changed the `core` setting, those cycles never disappeared for the exercises that we discussed moving _into_ the core.

> By definition a core exercise should unlocked by something else

Yeah, but that is not the case for [many of r's core exercises](https://github.com/exercism/r/blob/e40d74fff8d08d0a1bfb3fed57c09912d42d0e58/config.json). Thus, we were relying on the fall-back / ordering a lot, and that seems to take precedence in the graph drawing.

**Comment by jonmcalder** [comment]
> Should have taken more screenshots. Even when I changed the core setting, those cycles never disappeared for the exercises that we discussed moving into the core.

Well that's not the case for me, so there must have been something different going on in your config. Even with just the one screenshot you shared above, that tells us that you likely still had `bob` configured as a core exercise (since that is determined directly from the json and we can see the node is blue like the other core exercises).

My guess is that you still had `bob` as core, but marked it as unlocked by `anagram` (hence the link between those 2), and had `bob` after `rotational-cypher` in the json, hence the link there between those 2 core exercises.

> Yeah, but that is not the case for many of r's core exercises. Thus, we were relying on the fall-back / ordering a lot, and that seems to take precedence in the graph drawing.

`configlet lint` returns an error if you try and make a core exercise unlocked by another exercise. I think you've forgotten how the config works. Unlocking is only for side exercises and the core track is entirely determined by ordering in the json.

I shouldn't have framed it as core exercises being 'unlocked' (even though one tends to think of it that way), they are simply ordered (core) exercises within the track that may unlock other (unordered) exercises.

**Comment by katrinleinweber** [comment]
> forgotten how the config works

plus

> framed it as core exercises being 'unlocked'

were indeed the causes of this issue 🙄

I found the description now: ["sequence order in [`config.json`] determines the default order in which the exercises are fetched"](https://github.com/exercism/r/blame/e40d74fff8d08d0a1bfb3fed57c09912d42d0e58/README.md#L89).

My apologies! When I only thought about that explanation, it seemed too brittle a strategy for the Exercism web-app, and I deemed the above mentioned `!is.na(…)` code to be the more likely culprit.

**Comment by jonmcalder** [comment]
It's not only you - I also had to do a double take on how the config worked (since the json ordering thing does indeed seem a little brittle) but I seem to recall there was lots of passionate debate before that decision was taken 😉

I'm still pleasantly surprised that my now more than 2 year old code (randomly thrown together over a weekend if I recall correctly)  still gets a job done - so no worries for doubting it. I probably would have too! 🤣
